import { SystemDesignTopic } from '../../types/systemDesign';

export const newsFeedTopic: SystemDesignTopic = {
  id: 'news-feed',
  title: 'News Feed (Twitter, X)',
  subtitle: 'Timeline Aggregation & Fanout Engine',
  category: 'Distributed Systems',
  difficulty: 'Hard',
  frequencyRank: 2,
  editorial: {
    companies: ['Meta', 'Twitter/X', 'LinkedIn', 'ByteDance'],
    overview: 'Design a News Feed system that aggregates updates, posts, and media from followed entities into a real-time, chronological or ranked timeline.',
    introduction: `A news feed is a continuously updating list of stories, posts, photos, and activities generated by people you follow. Twitter timeline and Facebook News Feed are benchmark examples.

The core engineering challenge lies in balancing write fan-out (push model) vs read fan-out (pull model) when handling celebrity accounts (e.g. Elon Musk with 100M+ followers).`,
    requirements: {
      functional: [
        'User can publish new posts (tweets) containing text, images, or video links.',
        'User can view their personalized home news feed containing posts from followed users.',
        'Users can follow/unfollow other users.',
        'Feed updates in real-time or near real-time (< 500ms delivery).'
      ],
      nonFunctional: [
        'Low feed retrieval latency (< 200ms).',
        'High read-to-write ratio (typically 100:1).',
        'High availability and durability for post data.',
        'Scalable to 500M active daily users and 100K posts/sec bursts.'
      ],
      outOfScope: ['Live streaming', 'Encrypted Direct Messaging']
    },
    keyQuestions: {
      assumptions: [
        '300 Million Daily Active Users (DAU)',
        'Average user views timeline 10 times a day => 3 Billion feed reads/day',
        'Each user creates on average 2 posts per day => 600 Million posts/day (~7,000 write QPS, 50,000 peak QPS)'
      ],
      calculations: [
        { label: 'Read QPS', value: '35,000 QPS average (350,000 peak)', desc: '3B reads / 86400 seconds' },
        { label: 'Post Storage / day', value: '300 GB / day', desc: '600M posts * 500 bytes text metadata' },
        { label: 'Media Storage / day', value: '30 TB / day', desc: 'Assuming 20% posts include compressed image (250 KB avg)' }
      ]
    },
    dataModel: {
      overview: 'Separation of User Graph (Graph DB / MySQL), Post Store (NoSQL DB), and Feed Cache (Redis In-Memory Data Structure).',
      entities: [
        {
          name: 'users',
          description: 'User profile metadata.',
          fields: [
            { name: 'user_id', type: 'BIGINT PRIMARY KEY', desc: 'Unique ID' },
            { name: 'username', type: 'VARCHAR(64)', desc: 'User handler' },
            { name: 'created_at', type: 'TIMESTAMP', desc: 'Account creation time' }
          ]
        },
        {
          name: 'follows',
          description: 'Follow relationship table.',
          fields: [
            { name: 'follower_id', type: 'BIGINT', desc: 'User who follows' },
            { name: 'followee_id', type: 'BIGINT', desc: 'User being followed' },
            { name: 'created_at', type: 'TIMESTAMP', desc: 'Follow timestamp' }
          ]
        },
        {
          name: 'posts',
          description: 'Tweets or post content store.',
          fields: [
            { name: 'post_id', type: 'BIGINT PRIMARY KEY', desc: 'Snowflake ID (time-sorted)' },
            { name: 'user_id', type: 'BIGINT', desc: 'Author user ID' },
            { name: 'content', type: 'TEXT', desc: 'Text content' },
            { name: 'media_urls', type: 'JSON', desc: 'S3 asset URL links' },
            { name: 'created_at', type: 'TIMESTAMP', desc: 'Timestamp' }
          ]
        }
      ]
    },
    apiDesign: {
      overview: 'RESTful API or gRPC endpoints for post creation and feed retrieval.',
      endpoints: [
        {
          method: 'POST',
          path: '/v1/me/posts',
          params: '{ "content": "string", "mediaIds": [] }',
          statusCode: '201 Created',
          description: 'Publish a new post.'
        },
        {
          method: 'GET',
          path: '/v1/me/feed',
          params: '?page_size=20&max_id=snowflake_id',
          statusCode: '200 OK',
          description: 'Fetch paginated timeline feed for authenticated user.'
        }
      ]
    },
    basicImplementation: {
      title: 'Fan-out on Read (Pull Model)',
      description: 'When a post is published, it is stored in DB. When a user requests their news feed, the server queries the database for all users they follow, fetches their latest posts, and merges/sorts them in memory on demand.',
      drawbacks: [
        'Extremely slow read performance. Generating feed requires SQL JOINs over thousands of followees.',
        'High database load during peak traffic.'
      ]
    },
    advancedImplementation: {
      title: 'Hybrid Fan-out Engine (Push for normal users, Pull for Celebrities)',
      description: `Combines Fan-out on Write (Push) for 99% of normal users with Fan-out on Read (Pull) for high-follower celebrity accounts (>10,000 followers).

For normal users: When posting, a message queue triggers a Fan-out Service that injects the post_id directly into the Redis memory feed list of all active followers.

For celebrity users: Posts are saved to DB without pushing to millions of timelines. When a follower requests their feed, the system fetches their Redis cached feed and merges the latest posts from celebrities they follow at read time.`,
      components: [
        { name: 'Message Queue (Apache Kafka)', role: 'Async Event Bus', details: 'Buffers incoming posts and decouples post submission from timeline distribution.' },
        { name: 'Fan-out Service Workers', role: 'Push Execution', details: 'Fetches followers list from Graph DB and pushes post_id into followers Redis Feed Lists.' },
        { name: 'Timeline Cache (Redis Cluster)', role: 'In-Memory Feed Storage', details: 'Stores user timeline as sorted set (ZSET) indexed by Snowflake Post ID.' },
        { name: 'Media Storage (S3 + Cloudflare CDN)', role: 'Static Asset Hosting', details: 'Caches and serves images/videos worldwide.' }
      ]
    },
    flows: [
      {
        title: 'Publish Post Flow (Hybrid)',
        description: 'Processing new post submission.',
        steps: [
          'User submits POST /v1/me/posts.',
          'Post Service writes post to PostgreSQL/Cassandra DB.',
          'Post Service publishes event to Kafka topic `post-created`.',
          'Fan-out Service checks author follower count.',
          'If followers < 10,000 (Normal User): Push post_id to Redis timeline cache of all followers.',
          'If followers >= 10,000 (Celebrity): Store in Celebrity Post Cache without pushing.'
        ]
      },
      {
        title: 'Retrieve Feed Flow',
        description: 'User loading home timeline.',
        steps: [
          'User sends GET /v1/me/feed.',
          'Feed Service queries Redis timeline cache for user (`ZREVRANGEBYSCORE`).',
          'Feed Service identifies followed celebrities and queries Celebrity Cache for latest posts.',
          'Merges normal feed posts and celebrity posts in memory.',
          'Fetches full post content and media metadata for post_ids from Post Cache/DB and returns JSON.'
        ]
      }
    ],
    additionalPoints: [
      { topic: 'Snowflake ID Generation', details: 'Using Twitter Snowflake 64-bit integer IDs (Epoch timestamp + datacenter ID + worker ID + sequence number) guarantees posts are sortable by creation time without DB auto-increment lock.' },
      { topic: 'Feed Ranker / ML Recommendation', details: 'Chronological feeds can be augmented with ML ranking model (like Heavy Ranker) scoring post engagement probability (likes, retweets, replies).' }
    ]
  },
  quiz: [
    {
      id: 'q1',
      question: 'What is the main bottleneck of a pure "Fan-out on Write (Push)" approach in a news feed system?',
      options: [
        'Celebrities with millions of followers create massive write bursts, requiring millions of cache updates for a single post',
        'Read latency is too slow for normal users',
        'Database storage runs out immediately',
        'Images cannot be uploaded'
      ],
      correctAnswerIndex: 0,
      explanation: 'If a user with 100M followers posts, a pure Push architecture requires 100M Redis cache writes immediately, causing hot key bottlenecks and system lag (Hotspot Problem).'
    },
    {
      id: 'q2',
      question: 'Why are Twitter Snowflake IDs preferred over standard UUIDs for post IDs in news feed architectures?',
      options: [
        'Snowflake IDs include a 41-bit timestamp prefix, making them naturally time-ordered without requiring database sorting queries',
        'Snowflake IDs take less space than strings',
        'Snowflake IDs are completely random',
        'UUIDs cannot be indexed in NoSQL databases'
      ],
      correctAnswerIndex: 0,
      explanation: 'Snowflake 64-bit IDs start with epoch millisecond timestamps, ensuring post IDs automatically sort chronologically across distributed nodes.'
    }
  ],
  whiteboard: {
    nodes: [
      { id: 'client', label: 'Client App', type: 'client', description: 'Web/Mobile Client', x: 40, y: 160 },
      { id: 'lb', label: 'Load Balancer', type: 'lb', description: 'Distributes API traffic', x: 200, y: 160 },
      { id: 'postService', label: 'Post Service', type: 'service', description: 'Handles post creation', x: 380, y: 80 },
      { id: 'feedService', label: 'Feed Service', type: 'service', description: 'Retrieves user feed', x: 380, y: 240 },
      { id: 'kafka', label: 'Kafka Event Queue', type: 'queue', description: 'Post-created event queue', x: 560, y: 80 },
      { id: 'fanout', label: 'Fan-out Workers', type: 'service', description: 'Pushes post IDs to follower feeds', x: 740, y: 80 },
      { id: 'feedCache', label: 'Redis Feed Cache', type: 'cache', description: 'Stores user timeline ZSETs', x: 740, y: 240 },
      { id: 'postDb', label: 'Post Cassandra DB', type: 'db', description: 'Persistent post storage', x: 560, y: 320 }
    ],
    connections: [
      { from: 'client', to: 'lb', label: 'API Call' },
      { from: 'lb', to: 'postService', label: 'POST /post' },
      { from: 'lb', to: 'feedService', label: 'GET /feed' },
      { from: 'postService', to: 'kafka', label: 'Publish Event' },
      { from: 'kafka', to: 'fanout', label: 'Consume Event' },
      { from: 'fanout', to: 'feedCache', label: 'Update Timeline ZSET' },
      { from: 'feedService', to: 'feedCache', label: 'Fetch Feed IDs' },
      { from: 'feedService', to: 'postDb', label: 'Hydrate Post Details' }
    ]
  }
};
